// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTy2FoTk3OKiSBqK1AIu2nM1u71O_Vny8',
    appId: '1:652492894953:web:2ae65defd361747c3a7678',
    messagingSenderId: '652492894953',
    projectId: 'dog-decision-game',
    authDomain: 'dog-decision-game.firebaseapp.com',
    storageBucket: 'dog-decision-game.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrTtQqVLIoLawKvxCR1nDTR3NJEXHmzNk',
    appId: '1:652492894953:android:223b92fed86b6d513a7678',
    messagingSenderId: '652492894953',
    projectId: 'dog-decision-game',
    storageBucket: 'dog-decision-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLwVE6BFfLFQaZFNlvz2iACR0gwHcfI-I',
    appId: '1:652492894953:ios:5e35966abce0c39f3a7678',
    messagingSenderId: '652492894953',
    projectId: 'dog-decision-game',
    storageBucket: 'dog-decision-game.firebasestorage.app',
    iosBundleId: 'com.example.dogDecisionGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLwVE6BFfLFQaZFNlvz2iACR0gwHcfI-I',
    appId: '1:652492894953:ios:5e35966abce0c39f3a7678',
    messagingSenderId: '652492894953',
    projectId: 'dog-decision-game',
    storageBucket: 'dog-decision-game.firebasestorage.app',
    iosBundleId: 'com.example.dogDecisionGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTy2FoTk3OKiSBqK1AIu2nM1u71O_Vny8',
    appId: '1:652492894953:web:01fcc270ef24a5193a7678',
    messagingSenderId: '652492894953',
    projectId: 'dog-decision-game',
    authDomain: 'dog-decision-game.firebaseapp.com',
    storageBucket: 'dog-decision-game.firebasestorage.app',
  );
}
